### ISSUE TITLE
how to create the soft mask label ?

### ISSUE THREAD

**Issue by ztyxd** [STVIR/PMTD#18]
I cannot find the code to create the soft mask label, can you give me some suggestions?

**Comment by JingChaoLiu** [comment]
Sorry for the disorganized structure. See here, https://github.com/STVIR/PMTD/issues/5#issuecomment-529963848

**Comment by ztyxd** [comment]
thank you very much



---Original---

**Comment by xxlxx1** [comment]
@JingChaoLiu hi, so I can't train with soft mask label in project in early version ?
